/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LibTag {
    }
    interface LibTagInput {
    }
}
declare global {
    interface HTMLLibTagElement extends Components.LibTag, HTMLStencilElement {
    }
    var HTMLLibTagElement: {
        prototype: HTMLLibTagElement;
        new (): HTMLLibTagElement;
    };
    interface HTMLLibTagInputElement extends Components.LibTagInput, HTMLStencilElement {
    }
    var HTMLLibTagInputElement: {
        prototype: HTMLLibTagInputElement;
        new (): HTMLLibTagInputElement;
    };
    interface HTMLElementTagNameMap {
        "lib-tag": HTMLLibTagElement;
        "lib-tag-input": HTMLLibTagInputElement;
    }
}
declare namespace LocalJSX {
    interface LibTag {
    }
    interface LibTagInput {
    }
    interface IntrinsicElements {
        "lib-tag": LibTag;
        "lib-tag-input": LibTagInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lib-tag": LocalJSX.LibTag & JSXBase.HTMLAttributes<HTMLLibTagElement>;
            "lib-tag-input": LocalJSX.LibTagInput & JSXBase.HTMLAttributes<HTMLLibTagInputElement>;
        }
    }
}
